# Generated by Django 2.2.2 on 2019-06-16 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2019)),
                ('type', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Statment_element_headers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Statement')),
            ],
        ),
        migrations.CreateModel(
            name='Statement_element_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=255)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Statement')),
            ],
        ),
        migrations.CreateModel(
            name='Statement_element_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=455)),
                ('value', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Company')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Statment_element_headers')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Statement')),
            ],
        ),
    ]
